using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TwentyOne
{
    //CREATE CLASS 'Employee' THAT INHERITS SUPERCLASS 'Person' 
    public class Employee : Person
    {
        //CREATE PUBLIC PROPERTY 'Id' AS TYPE INTEGER
        public int Id { get; set; }
    }
}

//namespace TwentyOne
//{
//    //CREATE PUBLIC CLASS 'TwentyOneGame' THAT INHERITS THE SUPERCLASS 'Game' 
//    public class TwentyOneGame : Game
//    {
//        public override void Play() //'override' LETS US INHERIT THE CLASS 'Game' SINCE 'Play' IS AN ABSTRACT METHOD THAT MUST BE IMPLEMENTED FROM THE 'Game' SUPERCLASS
//        {
//            throw new NotImplementedException();
//        }
//        public override void ListPlayers()
//        {
//            Console.WriteLine("21 PLAYERS: ");
//            base.ListPlayers(); //THIS GETS AUTOGENERATED WHEN USING THE 'override' KEYWORD
//        }
//    }
//}
